ALTER TABLE employees ADD COLUMN IF NOT EXISTS job_profile VARCHAR(100);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(20);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(20);
